In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\oscar\Documents\DATASCIENCEOF\2026-02-BILBAO-FT-Data-Science\housing.csv")
df.head(5)

,id,title,price,surface,bedrooms,restrooms,features,description,rent,location_name,is_province
0,8459,"Piso de alquiler en Rúa Eugenio Carre Aldao, O...",630,85,3,2,"3 habs.,2 baños,85 m²,2ª Planta",CURSO ESCOLAR. INTERNET INCLUIDO. Vivienda con...,1,A Coruña,1
1,8460,"Piso de alquiler en Rúa Rodrigo a de Santiago,...",450,70,3,1,"3 habs.,1 baño,70 m²,4ª Planta",Vivienda muy soleada de 3 habitaciones semiamu...,1,A Coruña,1
2,8461,"Piso de alquiler en Avenida Novo Mesoiro, Mesoiro",600,90,3,2,"3 habs.,2 baños,90 m²,Ascensor,Calefacción",Las tres habitaciones disponen de armario y ca...,1,A Coruña,1
3,8463,"Piso de alquiler en Rúa Rianxo, Cuatro Caminos...",650,80,3,1,"3 habs.,1 baño,80 m²",NaN,1,A Coruña,1
4,8464,"Piso de alquiler en Rúa Rianxo, Cuatro Caminos...",650,80,3,1,"3 habs.,1 baño,80 m²,Ascensor,Calefacción",NaN,1,A Coruña,1

## Limpieza, eliminamos registros no reales

In [5]:
df_clean = df[
    (df['rent']== 1)&
    (df['price'] > 0) & (df['price'] < 5000) &
    (df['surface'] > 0) & (df['surface'] < 300) &
    (df['bedrooms'] > 0) & (df['bedrooms'] <= 10) &
    (df['restrooms'] > 0) & (df['restrooms'] <= 5)
].copy()

print(f"Filas tras limpieza: {len(df_clean)}")
print(f"Filas eliminadas: {len(df) - len(df_clean)}")

Filas tras limpieza: 93066
Filas eliminadas: 8299

In [6]:
df.head()

,id,title,price,surface,bedrooms,restrooms,features,description,rent,location_name,is_province
0,8459,"Piso de alquiler en Rúa Eugenio Carre Aldao, O...",630,85,3,2,"3 habs.,2 baños,85 m²,2ª Planta",CURSO ESCOLAR. INTERNET INCLUIDO. Vivienda con...,1,A Coruña,1
1,8460,"Piso de alquiler en Rúa Rodrigo a de Santiago,...",450,70,3,1,"3 habs.,1 baño,70 m²,4ª Planta",Vivienda muy soleada de 3 habitaciones semiamu...,1,A Coruña,1
2,8461,"Piso de alquiler en Avenida Novo Mesoiro, Mesoiro",600,90,3,2,"3 habs.,2 baños,90 m²,Ascensor,Calefacción",Las tres habitaciones disponen de armario y ca...,1,A Coruña,1
3,8463,"Piso de alquiler en Rúa Rianxo, Cuatro Caminos...",650,80,3,1,"3 habs.,1 baño,80 m²",NaN,1,A Coruña,1
4,8464,"Piso de alquiler en Rúa Rianxo, Cuatro Caminos...",650,80,3,1,"3 habs.,1 baño,80 m²,Ascensor,Calefacción",NaN,1,A Coruña,1

In [7]:
df.tail()

,id,title,price,surface,bedrooms,restrooms,features,description,rent,location_name,is_province
101360,2576468,Dúplex de alquiler en Calle Federico García Lo...,675,86,2,2,"2 habs.,2 baños,86 m²,11ª Planta,Ascensor",MAGNIFICO DUPLEX EN ZONA MUY TRANQUILA DE LA M...,1,Zaragoza,1
101361,2576469,Piso de alquiler en Calle Monasterio de Obarra...,650,63,2,1,"2 habs.,1 baño,63 m²,4ª Planta,Ascensor",Cuarte de Huerva.- Calle Monasterio de Obarra....,1,Zaragoza,1
101362,2576470,Casa adosada de alquiler en Zuera,700,175,3,2,"3 habs.,2 baños,175 m²,Calefacción",Se alquila o se vende unifamiliar en zona resi...,1,Zaragoza,1
101363,2576471,"Piso de alquiler en Calle Goya, San Mateo de G...",525,65,2,1,"2 habs.,1 baño,65 m²,Ascensor,Calefacción","Piso en San Mateo de Gallego, muy cercano a lo...",1,Zaragoza,1
101364,2576472,Casa adosada de alquiler en Calle Río Aguas Vi...,725,211,4,4,"4 habs.,4 baños,211 m²,Terraza,Balcón",Precioso unifamiliar adosado totalmente amuebl...,1,Zaragoza,1

In [8]:
df[df.features.str.contains("Terraza", na=False)]

,id,title,price,surface,bedrooms,restrooms,features,description,rent,location_name,is_province
34,8496,"Piso de alquiler en Rúa Adelaida Muro, Monte A...",450,60,2,1,"2 habs.,1 baño,60 m²,Bajos,Terraza","114-CRÑ - Piso muy luminoso, cercano al paseo...",1,A Coruña,1
37,8499,"Piso de alquiler en Rúa San Jaime, Sagrada Fam...",450,55,2,1,"2 habs.,1 baño,55 m²,Bajos,Terraza",'Situado entre Rd. Nelle y Av. Arteixo'._ ESTU...,1,A Coruña,1
59,8530,"Piso de alquiler en Vereda Polvorín, Monte Alt...",680,80,2,1,"2 habs.,1 baño,80 m²,Ascensor,Terraza","Piso en Montealto, primero con ascensor, refor...",1,A Coruña,1
60,8531,"Piso de alquiler en Vereda Polvorín, Monte Alt...",680,80,2,1,"2 habs.,1 baño,80 m²,Terraza,Calefacción",NaN,1,A Coruña,1
63,8536,"Dúplex de alquiler en Avenida Rubine, Centro -...",1500,158,4,4,"4 habs.,4 baños,158 m²,Ascensor,Terraza",Esta vivienda se alquila sin amueblar y estará...,1,A Coruña,1
...,...,...,...,...,...,...,...,...,...,...,...
101348,2398995,"Ático de alquiler en Calle León XIII, Centro",900,64,2,2,"2 habs.,2 baños,64 m²,Ascensor,Terraza",Houzi inmobiliaria alquila este ático recién r...,1,Zaragoza,1
101352,2576454,Casa o chalet de alquiler en Utebo,1500,217,6,3,"6 habs.,3 baños,217 m²,Terraza,Calefacción",Se alquila esplendido chalet independiente en ...,1,Zaragoza,1
101356,2576463,"Ático de alquiler en Calle Navas, 34, Zuera",450,129,4,1,"4 habs.,1 baño,129 m²,4ª Planta,Terraza",Se alquila vivienda situada en Calle Navas de ...,1,Zaragoza,1
101358,2576466,Casa o chalet de alquiler en Calle Los Arenale...,450,100,3,1,"3 habs.,1 baño,100 m²,Terraza","Casa con vistas inmejorables del municipio, si...",1,Zaragoza,1
101364,2576472,Casa adosada de alquiler en Calle Río Aguas Vi...,725,211,4,4,"4 habs.,4 baños,211 m²,Terraza,Balcón",Precioso unifamiliar adosado totalmente amuebl...,1,Zaragoza,1

In [12]:
df['features_list'] = df['features'].str.split(',\s*')

In [13]:
df['m2'] = df['features'].str.extract(r'(\d+)\s*m2').astype(float)
df['habitaciones'] = df['features'].str.extract(r'(\d+)\s*hab').astype(float)
df['baños'] = df['features'].str.extract(r'(\d+)\s*bañ').astype(float)

In [14]:
amenities = ['Terraza', 'Ascensor', 'Piscina', 'Calefaccion']

for a in amenities:
    df[a] = df['features'].str.contains(a, case=False, na=False).astype(int)

In [30]:
df.head(20)

,id,title,price,surface,bedrooms,restrooms,features,description,rent,location_name,is_province,features_list,m2,habitaciones,baños,Terraza,Ascensor,Piscina,Calefaccion
0,8459,"Piso de alquiler en Rúa Eugenio Carre Aldao, O...",630,85,3,2,"3 habs.,2 baños,85 m²,2ª Planta",CURSO ESCOLAR. INTERNET INCLUIDO. Vivienda con...,1,A Coruña,1,"[3 habs., 2 baños, 85 m², 2ª Planta]",NaN,3.0,2.0,0,0,0,0
1,8460,"Piso de alquiler en Rúa Rodrigo a de Santiago,...",450,70,3,1,"3 habs.,1 baño,70 m²,4ª Planta",Vivienda muy soleada de 3 habitaciones semiamu...,1,A Coruña,1,"[3 habs., 1 baño, 70 m², 4ª Planta]",NaN,3.0,1.0,0,0,0,0
2,8461,"Piso de alquiler en Avenida Novo Mesoiro, Mesoiro",600,90,3,2,"3 habs.,2 baños,90 m²,Ascensor,Calefacción",Las tres habitaciones disponen de armario y ca...,1,A Coruña,1,"[3 habs., 2 baños, 90 m², Ascensor, Calefacción]",NaN,3.0,2.0,0,1,0,0
3,8463,"Piso de alquiler en Rúa Rianxo, Cuatro Caminos...",650,80,3,1,"3 habs.,1 baño,80 m²",NaN,1,A Coruña,1,"[3 habs., 1 baño, 80 m²]",NaN,3.0,1.0,0,0,0,0
4,8464,"Piso de alquiler en Rúa Rianxo, Cuatro Caminos...",650,80,3,1,"3 habs.,1 baño,80 m²,Ascensor,Calefacción",NaN,1,A Coruña,1,"[3 habs., 1 baño, 80 m², Ascensor, Calefacción]",NaN,3.0,1.0,0,1,0,0
5,8465,Apartamento de alquiler en Avenida de Montserr...,525,55,1,1,"1 hab.,1 baño,55 m²,Ascensor,Parking","Bonito apartamento amplio , exterior y soleado...",1,A Coruña,1,"[1 hab., 1 baño, 55 m², Ascensor, Parking]",NaN,1.0,1.0,0,1,0,0
6,8466,"Piso de alquiler en Rúa San Andrés, Centro - J...",850,75,2,2,"2 habs.,2 baños,75 m²,Ascensor,Calefacción",Se alquila piso totalmente a estrenar incluido...,1,A Coruña,1,"[2 habs., 2 baños, 75 m², Ascensor, Calefacción]",NaN,2.0,2.0,0,1,0,0
7,8467,"Piso de alquiler en Rúa Puerto Rico, Os Mallos",600,85,3,1,"3 habs.,1 baño,85 m²,Ascensor",Se alquila piso a estudiantes. Situado en zona...,1,A Coruña,1,"[3 habs., 1 baño, 85 m², Ascensor]",NaN,3.0,1.0,0,1,0,0
8,8468,"Piso de alquiler en San Vicente, 42, Os Mallos",630,84,3,1,"3 habs.,1 baño,84 m²,3ª Planta","A partir del 1 de julio, se alquila este funci...",1,A Coruña,1,"[3 habs., 1 baño, 84 m², 3ª Planta]",NaN,3.0,1.0,0,0,0,0
9,8469,"Piso de alquiler en Rúa Manuel Piñeiro Pose, C...",650,72,3,2,"3 habs.,2 baños,72 m²,Ascensor,Calefacción",Piso en calle Manuel Piñeiro Pose (zona Corte ...,1,A Coruña,1,"[3 habs., 2 baños, 72 m², Ascensor, Calefacción]",NaN,3.0,2.0,0,1,0,0
10,8470,"Piso de alquiler en Avenida Fisterra, 24, Cent...",750,110,4,2,"4 habs.,2 baños,110 m²,1ª Planta,Calefacción",Piso amplio y soleado de 110m² útiles en pleno...,1,A Coruña,1,"[4 habs., 2 baños, 110 m², 1ª Planta, Calefacc...",NaN,4.0,2.0,0,0,0,0
11,8471,"Piso de alquiler en Rúa Capitán Juan Varela, O...",600,60,3,1,"3 habs.,1 baño,60 m²,5ª Planta,Ascensor","Piso en alquiler en calle Capitán Juan Varela,...",1,A Coruña,1,"[3 habs., 1 baño, 60 m², 5ª Planta, Ascensor]",NaN,3.0,1.0,0,1,0,0
12,8472,"Apartamento de alquiler en Noia, Os Mallos",675,71,2,2,"2 habs.,2 baños,71 m²,4ª Planta,Ascensor","Ya puedes vivir de alquiler , en una de la zon...",1,A Coruña,1,"[2 habs., 2 baños, 71 m², 4ª Planta, Ascensor]",NaN,2.0,2.0,0,1,0,0
13,8474,"Piso de alquiler en Ronda Monte Alto, 21, Mont...",500,52,1,1,"1 hab.,1 baño,52 m²,Ascensor,Calefacción",Disponible a partir de Julio. \n5º piso con as...,1,A Coruña,1,"[1 hab., 1 baño, 52 m², Ascensor, Calefacción]",NaN,1.0,1.0,0,1,0,0
14,8475,Apartamento de alquiler en Los Castros - Castr...,450,36,1,1,"1 hab.,1 baño,36 m²,Calefacción","LOS CASTROS , IMPECABLE APARTAMENTO DE UN DORM...",1,A Coruña,1,"[1 hab., 1 baño, 36 m², Calefacción]",NaN,1.0,1.0,0,0,0,0
15,8476,Piso de alquiler en Cuatro Caminos - Plaza de ...,675,90,3,2,"3 habs.,2 baños,90 m²,1ª Planta,Ascensor","PISO A UN PASO DEL CORTE INGLES , SE TRATA DE ...",1,A Coruña,1,"[3 habs., 2 baños, 90 m², 1ª Planta, Ascensor]",NaN,3.0,2.0,0,1,0,0
16,8478,Piso de alquiler en Os Mallos,500,86,3,1,"3 habs.,1 baño,86 m²,Ascensor","Alquilase piso, 500€, tres dormitorios, salón,...",1,A Coruña,1,"[3 habs., 1 baño, 86 m², Ascensor]",NaN,3.0,1.0,0,1,0,0
17,8479,Piso de alquiler en Os Mallos,570,75,3,1,"3 habs.,1 baño,75 m²,2ª Planta",LARGA TEMPORADA O CURSO ESCOLAR. PISO AMUEBLAD...,1,A Coruña,1,"[3 habs., 1 baño, 75 m², 2ª Planta]",NaN,3.0,1.0,0,0,0,0
18,8480,"Piso de alquiler en Concordia, Los Castros - C...",750,100,3,2,"3 habs.,2 baños,100 m²,5ª Planta,Calefacción","Se alquila piso en A Coruña, Avda de la Concor...",1,A Coruña,1,"[3 habs., 2 baños, 100 m², 5ª Planta, Calefacc...",NaN,3.0,2.0,0,0,0,0
19,8481,"Ático de alquiler en Papagayo, Monte Alto - Za...",650,36,1,1,"1 hab.,1 baño,36 m²,5ª Planta,Ascensor",PRECIOSO ESTUDIO EN ALQUILER A 3 MINUTOS DE LA...,1,A Coruña,1,"[1 hab., 1 baño, 36 m², 5ª Planta, Ascensor]",NaN,1.0,1.0,0,1,0,0

In [29]:
df['location_name'].unique().tolist()

['A Coruña',
 'Alacant',
 'Albacete',
 'Almería',
 'Araba',
 'Asturias',
 'Ávila',
 'Badajoz',
 'Barcelona',
 'Bizkaia',
 'Burgos',
 'Cáceres',
 'Cádiz',
 'Cantabria',
 'Castelló',
 'Ciudad Real',
 'Córdoba',
 'Cuenca',
 'Gipuzkoa',
 'Girona',
 'Granada',
 'Guadalajara',
 'Huelva',
 'Huesca',
 'Illes Balears',
 'Jaén',
 'La Rioja',
 'Las Palmas',
 'León',
 'Lleida',
 'Lugo',
 'Madrid',
 'Málaga',
 'Murcia',
 'Navarra',
 'Ourense',
 'Palencia',
 'Pontevedra',
 'Salamanca',
 'Santa Cruz de Tenerife',
 'Segovia',
 'Sevilla',
 'Soria',
 'Tarragona',
 'Teruel',
 'Toledo',
 'Valencia',
 'Valladolid',
 'Zamora',
 'Zaragoza']