## Competiciones de ML de kaggle





Final: martes 28 de abril.





Datos en un csv y hacer un modelo predictivo.



train.csv, entrenar aquí e modelo. Tiene columna de precios.

test.csv no lleva el precio. En el test se aplica lo predicho en el train. Datos de producción.

sample.csv, tiene predicciones muy malas, pero es un ejemplo.



Resultado: csv con dos columnas, id y precio.

<200 MAE, ok. <100 MAE, es posible.



Si se usa IA saber explicar lo que pasa.





Lanzar un get dummies a pandas para que genere las columnas numéricas: pasa categóricas a numéricas.

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import seaborn as sns

df = pd.read_csv('train.csv')
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4GB,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.2kg,669.0
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.2kg,1695.0
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.85kg,779.0
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29kg,2240.0
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32kg,825.0

In [3]:
df["Weight"] = df["Weight"].str.replace("kg", "").astype(float)     ## limpiar columna numerica
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4GB,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.20,669.0
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.20,1695.0
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.85,779.0
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29,2240.0
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32,825.0

In [4]:
df["Ram"] = df["Ram"].str.replace("GB", "").astype(int)         ## limpiar columna numerica
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.20,669.0
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.20,1695.0
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4,1TB HDD,Intel HD Graphics 620,Windows 10,1.85,779.0
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29,2240.0
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32,825.0

In [5]:
df["Resolution"] = df["ScreenResolution"].str.extract(r"(\d+x\d+)")     ## procesar screenresolution
df[["Width","Height"]] = df["Resolution"].str.split("x", expand=True).astype(int)
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Resolution,Width,Height
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.20,669.0,1920x1080,1920,1080
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.20,1695.0,1920x1080,1920,1080
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4,1TB HDD,Intel HD Graphics 620,Windows 10,1.85,779.0,1920x1080,1920,1080
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29,2240.0,3200x1800,3200,1800
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32,825.0,1920x1080,1920,1080

In [6]:
df["Cpu_freq"] = df["Cpu"].str.extract(r"(\d+\.\d+)").astype(float)     ## proesar CPU
df["Cpu_brand"] = df["Cpu"].str.split().str[0]
df["Cpu_model"] = df["Cpu"].str.extract(r"(i3|i5|i7|i9|Ryzen\s?\d)")
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Resolution,Width,Height,Cpu_freq,Cpu_brand,Cpu_model
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.20,669.0,1920x1080,1920,1080,0.9,Intel,NaN
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.20,1695.0,1920x1080,1920,1080,3.2,AMD,Ryzen 1
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4,1TB HDD,Intel HD Graphics 620,Windows 10,1.85,779.0,1920x1080,1920,1080,2.7,Intel,i7
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29,2240.0,3200x1800,3200,1800,2.5,Intel,i7
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32,825.0,1920x1080,1920,1080,2.5,Intel,i7

In [7]:
df["Gpu_brand"] = df["Gpu"].str.split().str[0]      ## procesar GPU
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,...,OpSys,Weight,Price_euros,Resolution,Width,Height,Cpu_freq,Cpu_brand,Cpu_model,Gpu_brand
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4,64GB Flash Storage,...,Chrome OS,1.20,669.0,1920x1080,1920,1080,0.9,Intel,NaN,Intel
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8,256GB SSD + 1TB HDD,...,Windows 10,3.20,1695.0,1920x1080,1920,1080,3.2,AMD,Ryzen 1,AMD
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4,1TB HDD,...,Windows 10,1.85,779.0,1920x1080,1920,1080,2.7,Intel,i7,Intel
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16,512GB SSD,...,Windows 10,1.29,2240.0,3200x1800,3200,1800,2.5,Intel,i7,Intel
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4,1.0TB Hybrid,...,Windows 7,2.32,825.0,1920x1080,1920,1080,2.5,Intel,i7,Intel

In [8]:
df = pd.get_dummies(df, drop_first=True)

In [9]:
import re               ## procesar memory

def parse_memory(mem):
    mem = mem.replace(" ", "")
    ssd = hdd = flash = hybrid = 0

    parts = mem.split("+")
    for p in parts:
        if "SSD" in p:
            ssd += int(re.findall(r"(\d+)", p)[0])
        elif "HDD" in p:
            hdd += int(re.findall(r"(\d+)", p)[0])
        elif "Flash" in p:
            flash += int(re.findall(r"(\d+)", p)[0])
        elif "Hybrid" in p:
            hybrid += int(re.findall(r"(\d+)", p)[0])
    return pd.Series([ssd, hdd, flash, hybrid])

df[["SSD","HDD","Flash","Hybrid"]] = df["Memory"].apply(parse_memory)
df.head()

KeyError: 'Memory'

In [ ]:
df = pd.get_dummies(df, columns=[                               ## one hot encoding, codificar categoricas en columnas si o no
    "Company","TypeName","OpSys","Cpu_brand","Gpu_brand"
], drop_first=True)
df.head()

,id,laptop_ID,Product,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,Weight,...,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS,Cpu_brand_Intel,Gpu_brand_Intel,Gpu_brand_Nvidia
0,697,705,Chromebook Flip,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4,64GB Flash Storage,Intel HD Graphics 515,1.20,...,False,False,False,False,False,False,False,True,True,False
1,435,442,Rog Strix,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8,256GB SSD + 1TB HDD,AMD Radeon RX 580,3.20,...,False,False,False,True,False,False,False,False,False,False
2,735,743,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4,1TB HDD,Intel HD Graphics 620,1.85,...,False,False,False,True,False,False,False,True,True,False
3,864,875,XPS 13,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16,512GB SSD,Intel Iris Plus Graphics 640,1.29,...,False,False,False,True,False,False,False,True,True,False
4,1176,1194,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4,1.0TB Hybrid,Intel HD Graphics 520,2.32,...,False,False,False,False,False,True,False,True,True,False

In [ ]:
df = df.drop(columns=[                          ## eliminar columnas inutiles
    "id","laptop_ID","Product","ScreenResolution","Cpu","Gpu","Memory"
])
df.head()

,Inches,Ram,Weight,Price_euros,Resolution,Width,Height,Cpu_freq,Cpu_model,SSD,...,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS,Cpu_brand_Intel,Gpu_brand_Intel,Gpu_brand_Nvidia
0,12.5,4,1.20,669.0,1920x1080,1920,1080,0.9,NaN,0,...,False,False,False,False,False,False,False,True,True,False
1,17.3,8,3.20,1695.0,1920x1080,1920,1080,3.2,Ryzen 1,256,...,False,False,False,True,False,False,False,False,False,False
2,15.6,4,1.85,779.0,1920x1080,1920,1080,2.7,i7,0,...,False,False,False,True,False,False,False,True,True,False
3,13.3,16,1.29,2240.0,3200x1800,3200,1800,2.5,i7,512,...,False,False,False,True,False,False,False,True,True,False
4,15.6,4,2.32,825.0,1920x1080,1920,1080,2.5,i7,0,...,False,False,False,False,False,True,False,True,True,False

In [ ]:
X = df.drop('Price_euros', axis=1)          ## separar x e y
y = df['Price_euros']

In [ ]:
from sklearn.preprocessing import StandardScaler                ## escalar variables numericas

num_cols = ["Inches","Weight","Ram","Width","Height","Cpu_freq","SSD","HDD","Flash","Hybrid"]
df[num_cols] = StandardScaler().fit_transform(df[num_cols])
df.head()

,Inches,Ram,Weight,Price_euros,Resolution,Width,Height,Cpu_freq,Cpu_model,SSD,...,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS,Cpu_brand_Intel,Gpu_brand_Intel,Gpu_brand_Nvidia
0,-1.814088,-0.853426,-1.295107,669.0,1920x1080,0.062237,0.042851,-2.809513,NaN,-1.028767,...,False,False,False,False,False,False,False,True,True,False
1,1.586337,-0.070009,1.739147,1695.0,1920x1080,0.062237,0.042851,1.728506,Ryzen 1,0.516379,...,False,False,False,True,False,False,False,False,False,False
2,0.382020,-0.853426,-0.308975,779.0,1920x1080,0.062237,0.042851,0.741980,i7,-1.028767,...,False,False,False,True,False,False,False,True,True,False
3,-1.247351,1.496824,-1.158566,2240.0,3200x1800,2.649590,2.571409,0.347370,i7,2.061524,...,False,False,False,True,False,False,False,True,True,False
4,0.382020,-0.853426,0.404075,825.0,1920x1080,0.062237,0.042851,0.347370,i7,-1.028767,...,False,False,False,False,False,True,False,True,True,False

In [ ]:
df.describe()

,Inches,Ram,Weight,Price_euros,Width,Height,Cpu_freq,SSD,HDD,Flash,Hybrid
count,9.120000e+02,9.120000e+02,9.120000e+02,912.00000,9.120000e+02,9.120000e+02,8.420000e+02,9.120000e+02,9.120000e+02,9.120000e+02,9.120000e+02
mean,2.031513e-15,1.129701e-16,-1.850372e-16,1126.92034,2.142536e-16,1.460820e-17,-1.434587e-16,1.402387e-16,-2.142536e-17,3.116416e-17,5.843279e-18
std,1.000549e+00,1.000549e+00,1.000549e+00,696.08887,1.000549e+00,1.000549e+00,1.000594e+00,1.000549e+00,1.000549e+00,1.000549e+00,1.000549e+00
min,-3.514300e+00,-1.245134e+00,-2.068842e+00,174.00000,-1.057602e+00,-1.052857e+00,-2.809513e+00,-1.028767e+00,-3.287804e-01,-1.398147e-01,-3.358807e-02
25%,-7.514553e-01,-8.534260e-01,-7.527346e-01,589.00000,-5.846014e-01,-5.892882e-01,-6.391564e-01,-1.028767e+00,-3.287804e-01,-1.398147e-01,-3.358807e-02
50%,3.820196e-01,-7.000928e-02,9.621779e-03,952.00000,6.223691e-02,4.285116e-02,3.473696e-01,-2.561940e-01,-3.287804e-01,-1.398147e-01,-3.358807e-02
75%,3.820196e-01,-7.000928e-02,3.889035e-01,1499.00000,6.223691e-02,4.285116e-02,7.419800e-01,5.163788e-01,-3.219667e-01,-1.398147e-01,-3.358807e-02
max,2.365601e+00,1.089783e+01,4.014837e+00,4899.00000,3.943267e+00,3.835687e+00,2.517727e+00,5.151816e+00,3.078038e+00,1.637983e+01,3.018237e+01

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 47 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Inches                912 non-null    float64
 1   Ram                   912 non-null    float64
 2   Weight                912 non-null    float64
 3   Price_euros           912 non-null    float64
 4   Resolution            912 non-null    str
 5   Width                 912 non-null    float64
 6   Height                912 non-null    float64
 7   Cpu_freq              842 non-null    float64
 8   Cpu_model             768 non-null    str
 9   SSD                   912 non-null    float64
 10  HDD                   912 non-null    float64
 11  Flash                 912 non-null    float64
 12  Hybrid                912 non-null    float64
 13  Company_Apple         912 non-null    bool
 14  Company_Asus          912 non-null    bool
 15  Company_Chuwi         912 non-null    bool
 16  Company_Dell          912 non-null    bool
 17  Company_Fujitsu       912 non-null    bool
 18  Company_Google        912 non-null    bool
 19  Company_HP            912 non-null    bool
 20  Company_Huawei        912 non-null    bool
 21  Company_LG            912 non-null    bool
 22  Company_Lenovo        912 non-null    bool
 23  Company_MSI           912 non-null    bool
 24  Company_Mediacom      912 non-null    bool
 25  Company_Microsoft     912 non-null    bool
 26  Company_Razer         912 non-null    bool
 27  Company_Samsung       912 non-null    bool
 28  Company_Toshiba       912 non-null    bool
 29  Company_Vero          912 non-null    bool
 30  Company_Xiaomi        912 non-null    bool
 31  TypeName_Gaming       912 non-null    bool
 32  TypeName_Netbook      912 non-null    bool
 33  TypeName_Notebook     912 non-null    bool
 34  TypeName_Ultrabook    912 non-null    bool
 35  TypeName_Workstation  912 non-null    bool
 36  OpSys_Chrome OS       912 non-null    bool
 37  OpSys_Linux           912 non-null    bool
 38  OpSys_Mac OS X        912 non-null    bool
 39  OpSys_No OS           912 non-null    bool
 40  OpSys_Windows 10      912 non-null    bool
 41  OpSys_Windows 10 S    912 non-null    bool
 42  OpSys_Windows 7       912 non-null    bool
 43  OpSys_macOS           912 non-null    bool
 44  Cpu_brand_Intel       912 non-null    bool
 45  Gpu_brand_Intel       912 non-null    bool
 46  Gpu_brand_Nvidia      912 non-null    bool
dtypes: bool(34), float64(11), str(2)
memory usage: 123.0 KB

## SVC

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Datos
X, y = load_iris(return_X_y=True)

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Modelo SVM
model = SVC(kernel='linear')  # kernel lineal
model.fit(X_train, y_train)

# Evaluación
accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9666666666666667

In [ ]:
model = SVC(kernel='rbf')

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

params = {
    'C': [0.1, 1, 10],
    'gamma': [0.01, 0.1, 1],
    'kernel': ['rbf']
}

grid = GridSearchCV(SVC(), params, cv=5)
grid.fit(X_train, y_train)

print("Mejores parámetros:", grid.best_params_)

Mejores parámetros: {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = SVC()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[13  0  0]
 [ 0  8  1]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.89      0.94         9
           2       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.96      0.96        30
weighted avg       0.97      0.97      0.97        30

## Train-test-split / Random forest

In [ ]:
# Variable objetivo
y = df["Cpu_freq"]

# Variables predictoras
X = df.drop(columns=["Price_euros"])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
score = model.score(X_test, y_test)         ## evaluar
print("R2:", score)

R2: 0.8285885493160299

In [ ]:
predicciones = model.predict(X_test[:5])            ## probar prediccion
print(predicciones)
print(y_test[:5].values)

[1255.27206     607.058925    740.2505      917.17176667  703.5985    ]
[1159.    579.    910.    970.9   769.15]

In [ ]:
import pandas as pd                                 ## importancias de cada feature
import numpy as np

importances = model.feature_importances_
feature_names = X_train.columns

feat_imp = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

feat_imp.head(20)

                 feature  importance
1                    Ram    0.509672
2                 Weight    0.095758
5               Cpu_freq    0.081701
30     TypeName_Notebook    0.069265
6                    SSD    0.059419
60          Cpu_model_i7    0.025358
0                 Inches    0.020575
32  TypeName_Workstation    0.020415
3                  Width    0.012649
16            Company_HP    0.011017
4                 Height    0.009906
59          Cpu_model_i5    0.009733
39       OpSys_Windows 7    0.007007
7                    HDD    0.006950
23         Company_Razer    0.006463
19        Company_Lenovo    0.006173
11          Company_Asus    0.005302
46  Resolution_1920x1080    0.005213
37      OpSys_Windows 10    0.004026
28       TypeName_Gaming    0.003906

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Valores reales y predichos
#y_true = [3, -0.5, 2, 7]
#y_pred = [2.5, 0.0, 2, 8]

# Métricas
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_true, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

MAE: 0.5
MSE: 0.375
RMSE: 0.6123724356957945
R2: 0.9486081370449679

In [ ]:
resultado = pd.DataFrame({              ## tabla de predicciones 
    'Real': y_test.values,
    'Predicho': predicciones
})

print(resultado.head(10))

In [ ]:
from sklearn.metrics import mean_absolute_error

print("Error medio (MAE):", mae)
# Métricas
mae = mean_absolute_error(y_true, y_pred)
mse = mean_squared_error(y_true, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_true, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

Error medio (MAE): 0.5
MAE: 0.5
MSE: 0.375
RMSE: 0.6123724356957945
R2: 0.9486081370449679

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris

# Datos
X, y = load_iris(return_X_y=True)

# Modelo
model = LogisticRegression(max_iter=200)

# Cross-validation (k=5)
scores = cross_val_score(model, X, y, cv=5)

print("Scores por fold:", scores)
print("Media:", scores.mean())

Scores por fold: [0.96666667 1.         0.93333333 0.96666667 1.        ]
Media: 0.9733333333333334